### PR TITLE
[Perl] Add test workflow to GHA

### PR DESCRIPTION
**Pull request by aurelien-reeves**

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
@ehuelsmann could you review that PR please?

In order to be able to execute the deserialize tests, I have added the compatibility kit into the test folder `perl/t`. I don't know if that is annoying or not. If it is, where would you suggest to put it?

**Comment by aurelien-reeves** [comment]
I merge the PR in order to move on. @ehuelsmann you can still post comments, we will be able to fix any undesired things in another PR :)

**Comment by ehuelsmann** [comment]
@aurelien-reeves Reviewed the PR. It looks good. `t/` is generally packaged and published on CPAN, but it's not indexed (not visible from e.g. MetaCPAN.org) and it's also not installed on target systems.

+1 to the PR.

**Review by ehuelsmann — COMMENTED** [review]
lgtm

**Pull request merged**
