### PR TITLE
Add exception to TestStepFinished TestRunFinished

### PR DESCRIPTION
**Pull request by mpkorstanje**
### 🤔 What's changed?

To implement a message based JUnit XML Formatter (https://github.com/cucumber/cucumber-junit-xml-formatter/pull/3) we need to know the class and message of the exception that caused the scenario to fail. This information is often included implicitly in the `message` field but can not be reliably extracted.

For example if a scenario failed duo to a assertion exception the failure should be rendered as:

```xml
<failure message="[The scenario has pending or undefined step(s)](expected: <\"a\"> but was: <\"b\">)" type="org.opentest4j.AssertionFailedError">
  <![CDATA[

... Detailed stack trace here

]]>
</failure>
```

Currently however we can only render the stack trace part. The other information is not available.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

Is this generic enough to work in other languages?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by davidjgoss** [comment]
> Is this generic enough to work in other languages?

I think it's okay at least from a JS persective. We can always provide a generic fallback if those fields are not present?

You mentioned the flatness of the structure before, I guess the alternative would be an `exception` sub-object with `type` and `message` fields - this would then be a natural place for additional granular detail about the exception to go e.g. actual vs expected when we eventually get to that.

**Comment by mpkorstanje** [comment]
Good one. There are some proposals to add more information about exceptions.

- https://github.com/cucumber/messages/issues/70
- https://github.com/cucumber/messages/issues/69

**Comment by mpkorstanje** [comment]
I've added an Exception object with `type` and `message` fields. I looked at adding `stacktrace` and `expected` and `actual` but it's a bit too much work to see that every language can do with stack traces.

**Comment by davidjgoss** [comment]
What's the use case for the exception on `TestRunFinished` out of interest?

**Comment by mpkorstanje** [comment]
To inform about exceptions that didn't happen in steps or global hooks.  For example in Cucumber JVM this would be related to creating the dependency injection container.

Cucumbers execution model can be seen as a tree of containers. Each container has a started and finished event. Each finished event should have an exception for exceptions that occurred in that container.

**Pull request merged**
